# Generated by Django 3.2.12 on 2023-04-18 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_type_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('name',)},
        ),
    ]
