# Generated by Django 3.2.12 on 2023-04-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_species_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='species',
            table=None,
        ),
    ]
