# Generated by Django 3.2.12 on 2023-04-18 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_type_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='type',
            table=None,
        ),
    ]
