# Generated by Django 3.2.12 on 2023-04-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_alter_species_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='species',
            table='species',
        ),
    ]
