# Generated by Django 3.2.12 on 2023-03-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_goodeats', '0003_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='updated_at',
            field=models.CharField(max_length=100),
        ),
    ]
