# Generated by Django 3.2.12 on 2023-03-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_goodeats', '0004_alter_ingredients_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
